export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      background: "hsl(var(--background))",
      foreground: "hsl(var(--foreground))",
      primary: {
        DEFAULT: "hsl(var(--primary))",
        foreground: "hsl(var(--primary-foreground))",
      },
      secondary: {
        DEFAULT: "hsl(var(--secondary))",
        foreground: "hsl(var(--secondary-foreground))",
      },
      muted: {
        DEFAULT: "hsl(var(--muted))",
        foreground: "hsl(var(--muted-foreground))",
      },
      accent: {
        DEFAULT: "hsl(var(--accent))",
        foreground: "hsl(var(--accent-foreground))",
      },
      destructive: {
        DEFAULT: "hsl(var(--destructive))",
        foreground: "hsl(var(--destructive-foreground))",
      },
      border: "hsl(var(--border))",
      input: "hsl(var(--input))",
      ring: "hsl(var(--ring))",
      card: {
        DEFAULT: "hsl(var(--card))",
        foreground: "hsl(var(--card-foreground))",
      },
      popover: {
        DEFAULT: "hsl(var(--popover))",
        foreground: "hsl(var(--popover-foreground))",
      },
      chart: {
        "1": "hsl(var(--chart-1))",
        "2": "hsl(var(--chart-2))",
        "3": "hsl(var(--chart-3))",
        "4": "hsl(var(--chart-4))",
        "5": "hsl(var(--chart-5))",
      },
      sidebar: {
        DEFAULT: "hsl(var(--sidebar))",
        foreground: "hsl(var(--sidebar-foreground))",
        primary: "hsl(var(--sidebar-primary))",
        "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        accent: "hsl(var(--sidebar-accent))",
        "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        border: "hsl(var(--sidebar-border))",
        ring: "hsl(var(--sidebar-ring))",
      },
      framer: {
        blue: {
          50: "hsl(var(--framer-blue-50))",
          100: "hsl(var(--framer-blue-100))",
          200: "hsl(var(--framer-blue-200))",
          300: "hsl(var(--framer-blue-300))",
          400: "hsl(var(--framer-blue-400))",
          500: "hsl(var(--framer-blue-500))",
          600: "hsl(var(--framer-blue-600))",
          700: "hsl(var(--framer-blue-700))",
          800: "hsl(var(--framer-blue-800))",
          900: "hsl(var(--framer-blue-900))",
        },
        purple: {
          50: "hsl(var(--framer-purple-50))",
          100: "hsl(var(--framer-purple-100))",
          200: "hsl(var(--framer-purple-200))",
          300: "hsl(var(--framer-purple-300))",
          400: "hsl(var(--framer-purple-400))",
          500: "hsl(var(--framer-purple-500))",
          600: "hsl(var(--framer-purple-600))",
          700: "hsl(var(--framer-purple-700))",
          800: "hsl(var(--framer-purple-800))",
          900: "hsl(var(--framer-purple-900))",
        },
        gray: {
          50: "hsl(var(--framer-gray-50))",
          100: "hsl(var(--framer-gray-100))",
          200: "hsl(var(--framer-gray-200))",
          300: "hsl(var(--framer-gray-300))",
          400: "hsl(var(--framer-gray-400))",
          500: "hsl(var(--framer-gray-500))",
          600: "hsl(var(--framer-gray-600))",
          700: "hsl(var(--framer-gray-700))",
          800: "hsl(var(--framer-gray-800))",
          900: "hsl(var(--framer-gray-900))",
        },
        success: "hsl(var(--framer-success))",
        warning: "hsl(var(--framer-warning))",
        error: "hsl(var(--framer-error))",
        info: "hsl(var(--framer-info))",
      },
    },
    borderRadius: {
      lg: "var(--radius)",
      md: "calc(var(--radius) - 2px)",
      sm: "calc(var(--radius) - 4px)",
    },
    fontFamily: {
      sans: ["var(--font-sans)", "sans-serif"],
      mono: ["var(--font-mono)", "monospace"],
      heading: ["var(--font-heading)", "sans-serif"],
    },
    fontSize: {
      "2xs": ["0.625rem", { lineHeight: "0.75rem" }],
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "1" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
    spacing: {
      "18": "4.5rem",
      "88": "22rem",
      "128": "32rem",
      "144": "36rem",
    },
    animation: {
      "fade-in": "fadeIn 0.5s ease-in-out",
      "fade-in-up": "fadeInUp 0.5s ease-out",
      "fade-in-down": "fadeInDown 0.5s ease-out",
      "fade-in-left": "fadeInLeft 0.5s ease-out",
      "fade-in-right": "fadeInRight 0.5s ease-out",
      "scale-in": "scaleIn 0.3s ease-out",
      "slide-in-bottom": "slideInFromBottom 0.5s ease-out",
      "bounce-gentle": "bounceGentle 1s infinite",
      "pulse-slow": "pulseSlow 3s ease-in-out infinite",
      "float": "float 6s ease-in-out infinite",
      "glow": "glow 2s ease-in-out infinite alternate",
      "shimmer": "shimmer 2s linear infinite",
      "gradient-x": "gradientX 15s ease infinite",
      "gradient-y": "gradientY 15s ease infinite",
      "gradient-xy": "gradientXY 15s ease infinite",
    },
    keyframes: {
      fadeIn: {
        "0%": { opacity: "0" },
        "100%": { opacity: "1" },
      },
      fadeInUp: {
        "0%": { opacity: "0", transform: "translateY(20px)" },
        "100%": { opacity: "1", transform: "translateY(0)" },
      },
      fadeInDown: {
        "0%": { opacity: "0", transform: "translateY(-20px)" },
        "100%": { opacity: "1", transform: "translateY(0)" },
      },
      fadeInLeft: {
        "0%": { opacity: "0", transform: "translateX(-20px)" },
        "100%": { opacity: "1", transform: "translateX(0)" },
      },
      fadeInRight: {
        "0%": { opacity: "0", transform: "translateX(20px)" },
        "100%": { opacity: "1", transform: "translateX(0)" },
      },
      scaleIn: {
        "0%": { opacity: "0", transform: "scale(0.8)" },
        "100%": { opacity: "1", transform: "scale(1)" },
      },
      slideInFromBottom: {
        "0%": { opacity: "0", transform: "translateY(100%)" },
        "100%": { opacity: "1", transform: "translateY(0)" },
      },
      bounceGentle: {
        "0%, 100%": { transform: "translateY(0)" },
        "50%": { transform: "translateY(-10px)" },
      },
      pulseSlow: {
        "0%, 100%": { opacity: "1" },
        "50%": { opacity: "0.5" },
      },
      float: {
        "0%, 100%": { transform: "translateY(0px)" },
        "50%": { transform: "translateY(-20px)" },
      },
      glow: {
        "0%": { boxShadow: "0 0 20px rgba(59, 130, 246, 0.5)" },
        "100%": { boxShadow: "0 0 30px rgba(59, 130, 246, 0.8)" },
      },
      shimmer: {
        "0%": { transform: "translateX(-100%)" },
        "100%": { transform: "translateX(100%)" },
      },
      gradientX: {
        "0%, 100%": { "background-position": "0% 50%" },
        "50%": { "background-position": "100% 50%" },
      },
      gradientY: {
        "0%, 100%": { "background-position": "50% 0%" },
        "50%": { "background-position": "50% 100%" },
      },
      gradientXY: {
        "0%, 100%": { "background-position": "0% 0%" },
        "50%": { "background-position": "100% 100%" },
      },
    },
    boxShadow: {
      "glow": "0 0 20px rgba(59, 130, 246, 0.5)",
      "glow-lg": "0 0 30px rgba(59, 130, 246, 0.6)",
      "glow-primary": "0 0 20px hsl(var(--primary) / 0.5)",
      "inner-glow": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
    },
    backgroundImage: {
      "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      "gradient-mesh": "radial-gradient(at 40% 20%, hsla(28,100%,74%,1) 0px, transparent 50%), radial-gradient(at 80% 0%, hsla(189,100%,56%,1) 0px, transparent 50%), radial-gradient(at 0% 50%, hsla(355,100%,93%,1) 0px, transparent 50%), radial-gradient(at 80% 50%, hsla(340,100%,76%,1) 0px, transparent 50%), radial-gradient(at 0% 100%, hsla(22,100%,77%,1) 0px, transparent 50%), radial-gradient(at 80% 100%, hsla(242,100%,70%,1) 0px, transparent 50%), radial-gradient(at 0% 0%, hsla(343,100%,76%,1) 0px, transparent 50%)",
    },
    backdropBlur: {
      xs: "2px",
    },
    transitionProperty: {
      "height": "height",
      "spacing": "margin, padding",
    },
    scale: {
      "102": "1.02",
      "103": "1.03",
      "98": "0.98",
      "97": "0.97",
    },
  },
  plugins: [],
}
